version: "3"
services:
  alart-app: #サービス名
    build: ./webpage # dockerイメージをbuildするディレクトリ指定(Dockerfileのあるディレクトリ)
    image: alart-web-image # dockerイメージ名
    container_name: alart-web # コンテナ名
    ports:
      - 8081:1234 # ポート接続 <メインOS側のポート>:<コンテナ内からのポート>
    volumes:
      - ./webpage/src:/app/src # 共有フォルダ(要検索)
    # command: node /app/src/index.js # コンテナ内での実行コマンド(要検索)
    tty: true 
    working_dir: /app/
  map-app:
    build: ./mappage
    image: map-app-image
    container_name: map-app
    ports:
      - 8080:5678
    volumes:
      - ./mappage/src:/app/src