version: "3"
services:
  revese-proxy: # リバースプロキシ
    image: nginx
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80 # ポート接続 <メインOS側のポート>:<コンテナ内からのポート>
  # store-srv: 
  #   build: ./store-srv
  #   image: store-srv-image
  #   container_name: store-srv
  #   ports: 
  #     - 4000:2000 # ポート接続 <メインOS側のポート>:<コンテナ内からのポート>
  #   volumes:
  #     - ./store-srv/src:/app/src
  #   command: node /app/src/server.js
  #   tty: true 
  #   init: true
  #   working_dir: /app/

  alart-app: # データが来た通信からUserに通知する
    build: ./webpage
    image: alart-web-image
    container_name: alart-web
    ports:
      - 8081:1234 # ポート接続 <メインOS側のポート>:<コンテナ内からのポート>
    volumes:
      - ./webpage/src:/app/src
    command: node /app/src/index.js
    tty: true 
    init: true
    working_dir: /app/

  map-app: # 送られてきたデータのビジュアライザ
    build: ./mappage
    image: map-app-image
    container_name: map-app
    ports:
      - 8080:5678 # ポート接続 <メインOS側のポート>:<コンテナ内からのポート>
    volumes:
      - ./mappage/src:/app/src
    command: node /app/src/server.js
    tty : true
    init: true
    working_dir: /app/