version: "3"
service:
  # リバースプロキシ
  # reverse-proxy:
  #   build: ./reverse-proxy
  #   image: reverse-proxy-img
  #   container_name: reverse-proxy
  #   ports:
  #     - 
  #   volumes:
  #     - 

  # 通知アプリ
  # notification-app:
  #   build: ./notification-app
  #   image: notification-app-img
  #   container_name: notification-app
  #   ports:
  #     - 
  #   volumes:
  #     - 

  # マップアプリ(ビジュアライザ)
  # visualizer-app:
  #   build: ./visualizer-app
  #   image: visualizer-app-img
  #   container_name: visualizer-app
  #   ports:
  #     - 
  #   volumes:
  #     - 

  # データ解析ノード
  # analizer-node:
  #   build: ./analizer-node
  #   image: analizer-node-img
  #   container_name: analizer-node
  #   ports:
  #     - 
  #   volumes:
  #     - 

  # データベースのAPI
  # database-api:
  #   build: ./database-api
  #   image: database-api-img
  #   container_name: database-api
  #   ports:
  #     - 
  #   volumes:
  #     - 

  # データベース
  # database:

# networks:
